# Generated by Django 4.0.6 on 2023-11-24 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import problems.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('priority', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reportDateTime', models.DateTimeField()),
                ('multipleAffectedUser', models.BooleanField()),
                ('affectedUserSize', models.IntegerField()),
                ('ticketDateTime', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('ticketNumber', models.IntegerField(default=problems.models.Problem.ids, unique=True)),
                ('isAssigned', models.BooleanField(default=False)),
                ('assignedTechId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemAssignedTech', to=settings.AUTH_USER_MODEL)),
                ('impact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemimpact_id', to='priority.priority', to_field='priority_id')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problempriority_id', to='priority.priority', to_field='priority_id')),
                ('security_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemSecGroup', to='users.securitygroup')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='priority.status', to_field='status_id')),
                ('ticketOwnerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemTicketOwner', to=settings.AUTH_USER_MODEL)),
                ('ticketOwnerSection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemSection', to='users.course')),
                ('urgency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemurgency_id', to='priority.priority', to_field='priority_id')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userProblemId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
