# Generated by Django 4.0.6 on 2024-02-14 05:32

import assets.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_status_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tag', models.IntegerField(default=1)),
                ('serial_number', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=100)),
                ('category', enumchoicefield.fields.EnumChoiceField(enum_class=assets.models.Categories, max_length=10)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_dependencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_version', models.CharField(blank=True, max_length=100, null=True)),
                ('license_name', models.CharField(blank=True, max_length=100, null=True)),
                ('license_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_support', models.BooleanField(blank=True, null=True)),
                ('license_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset_status', to_field='asset_status_id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
