# Generated by Django 4.0.6 on 2024-02-18 20:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=20)),
                ('ticket_number', models.CharField(max_length=100, unique=True)),
                ('request_name', models.CharField(max_length=50)),
                ('request_contact', models.CharField(max_length=50)),
                ('impact_slider', models.IntegerField()),
                ('urgency_slider', models.IntegerField()),
                ('priority_slider', models.IntegerField()),
                ('new_change_data_sheet', models.TextField()),
                ('recovery_available', models.BooleanField(default=False)),
                ('redundancy', models.CharField(blank=True, max_length=50, null=True)),
                ('change_history', models.CharField(blank=True, max_length=50, null=True)),
                ('testing_completed', models.BooleanField(default=False)),
                ('testing_desc', models.TextField(blank=True, null=True)),
                ('choose_environment', models.CharField(blank=True, max_length=50, null=True)),
                ('are_there_dependencies', models.BooleanField(default=False)),
                ('current_environment_maturity', models.CharField(blank=True, max_length=50, null=True)),
                ('documentation_of_config', models.CharField(blank=True, max_length=50, null=True)),
                ('adequate_install_window', models.BooleanField(default=False)),
                ('required_employees', models.CharField(blank=True, max_length=50, null=True)),
                ('install_desc', models.TextField(blank=True, null=True)),
                ('adequate_backout_window', models.BooleanField(default=False)),
                ('backout_difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('backout_desc', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('perm_or_temp', models.BooleanField(default=False)),
                ('time_to_implement', models.CharField(blank=True, max_length=50, null=True)),
                ('business_case_desc', models.TextField(blank=True, null=True)),
                ('assets', models.ManyToManyField(blank=True, to='assets.asset')),
                ('assigned_technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_technicians', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requesters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
