<<<<<<< HEAD
# Generated by Django 4.0.6 on 2024-02-12 04:09
=======
# Generated by Django 4.0.6 on 2023-11-24 19:31
>>>>>>> fde268c9814b79f49d05defa63c74f96c858c11b

import changes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('users', '0001_initial'),
        ('assets', '0001_initial'),
=======
        ('assets', '0001_initial'),
        ('users', '0001_initial'),
>>>>>>> fde268c9814b79f49d05defa63c74f96c858c11b
        ('priority', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requestNumber', models.CharField(default=changes.models.ChangeRequest.generate_ticket_number, max_length=20, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('requestType', models.CharField(max_length=100)),
                ('requestDateTime', models.DateTimeField()),
                ('projectName', models.CharField(max_length=100)),
                ('requestName', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('requestContact', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('isActive', models.BooleanField(default=True)),
                ('install_plan_description', models.CharField(max_length=300, null=True)),
                ('backout_plan_description', models.CharField(max_length=300, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('purpose', models.CharField(max_length=300, null=True)),
                ('need', models.CharField(max_length=300, null=True)),
                ('duration', models.CharField(max_length=300, null=True)),
                ('doc_config', models.CharField(max_length=100, null=True)),
                ('environment', models.CharField(max_length=100, null=True)),
                ('redundancy', models.CharField(max_length=100, null=True)),
                ('environment_maturity', models.CharField(max_length=100, null=True)),
                ('time_to_implement', models.CharField(max_length=100, null=True)),
                ('change_history', models.CharField(max_length=100, null=True)),
                ('deployment_window', models.CharField(max_length=100, null=True)),
                ('num_of_staff', models.CharField(max_length=100, null=True)),
                ('testing', models.CharField(max_length=100, null=True)),
                ('backout_plan_risk', models.CharField(max_length=100, null=True)),
                ('scheduling', models.CharField(max_length=100, null=True)),
                ('approvals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='changes.approvals')),
                ('assets', models.ManyToManyField(to='assets.asset')),
                ('assignedTechId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedToId', to=settings.AUTH_USER_MODEL)),
                ('impact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changeimpact_id', to='priority.priority', to_field='priority_id')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changepriority_id', to='priority.priority', to_field='priority_id')),
                ('requestOwnerSection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseId', to='users.course')),
                ('requestedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ChangeUserId', to=settings.AUTH_USER_MODEL)),
                ('ticketOwnerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ChangeTicketOwnerId', to=settings.AUTH_USER_MODEL)),
                ('urgency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changeurgency_id', to='priority.priority', to_field='priority_id')),
            ],
        ),
    ]
