# Generated by Django 4.0.6 on 2024-02-23 08:39

import changes.models
from django.db import migrations, models
import enumchoicefield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_status_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='changerequest',
            name='change_status',
            field=enumchoicefield.fields.EnumChoiceField(default=changes.models.ChangeStatus(1), enum_class=changes.models.ChangeStatus, max_length=16),
        ),
    ]
