# Generated by Django 4.0.6 on 2024-02-23 15:25

import changes.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0002_change_status_changerequest_change_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Change_Status',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='current_environment_maturity',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='redundancy',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='time_to_implement',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='duration',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.Duration(1), enum_class=changes.models.Duration, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='environment_maturity',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.EnvironmentMaturity(1), enum_class=changes.models.EnvironmentMaturity, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='redundancy_type',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.RedundancyTypes(1), enum_class=changes.models.RedundancyTypes, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='backout_difficulty',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.BackOutPlanDifficulty(1), enum_class=changes.models.BackOutPlanDifficulty, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='change_history',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.ChangeHistory(1), enum_class=changes.models.ChangeHistory, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='choose_environment',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.ChooseEnvironment(1), enum_class=changes.models.ChooseEnvironment, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='documentation_of_config',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.DocumentationOfConfiguration(1), enum_class=changes.models.DocumentationOfConfiguration, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='perm_or_temp',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.PermTemp(1), enum_class=changes.models.PermTemp, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='request_type',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.RequestType(1), enum_class=changes.models.RequestType, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='required_employees',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.RequiredEmployees(1), enum_class=changes.models.RequiredEmployees, max_length=5, null=True),
        ),
    ]
