# Generated by Django 4.0.6 on 2024-02-29 02:42

import changes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0003_delete_change_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='ticket_number',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='ticketNumber',
            field=models.CharField(default=changes.models.ChangeRequest.generate_ticket_number, max_length=20, unique=True),
        ),
    ]
