# Generated by Django 4.0.6 on 2024-02-29 21:22

import changes.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0004_remove_changerequest_ticket_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approvals',
        ),
        migrations.AlterModelOptions(
            name='changerequest',
            options={'verbose_name_plural': 'Change Requests'},
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='ticketNumber',
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='documentation_of_config',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.DocumentationOfConfiguration(1), enum_class=changes.models.DocumentationOfConfiguration, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='redundancy_type',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=changes.models.RedundancyTypes(1), enum_class=changes.models.RedundancyTypes, max_length=9, null=True),
        ),
    ]
