# Generated by Django 4.0.6 on 2023-11-24 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import incidents.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '__first__'),
        ('priority', '__first__'),
        ('slas', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticketNumber', models.CharField(default=incidents.models.Incident.generate_ticket_number, max_length=20, unique=True)),
                ('reportDateTime', models.DateTimeField()),
                ('multipleAffectedUser', models.BooleanField()),
                ('affectedUserSize', models.IntegerField()),
                ('ticketDateTime', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=300)),
                ('details', models.CharField(max_length=300)),
                ('isAssigned', models.BooleanField(default=False)),
                ('assignedTechId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedIncidentTech', to=settings.AUTH_USER_MODEL)),
                ('impact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentimpact_id', to='priority.priority', to_field='priority_id')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentpriority_id', to='priority.priority', to_field='priority_id')),
                ('problemsRelated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatedItems', to='problems.problem')),
                ('security_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secGroup', to='users.securitygroup')),
                ('slaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentSLA', to='slas.sla')),
                ('sla_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='slas.sla_status', to_field='status_id')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='priority.status', to_field='status_id')),
                ('ticketOwnerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IncidentTicketOwner', to=settings.AUTH_USER_MODEL)),
                ('ticketOwnerRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IncidentTicketrole', to='users.role', to_field='roleId')),
                ('ticketOwnerSection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentTicketCourse', to='users.course')),
                ('ticketType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentTicketType', to='incidents.tickettype')),
                ('urgency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidenturgency_id', to='priority.priority', to_field='priority_id')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userincidentId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
