# Generated by Django 4.0.6 on 2023-11-24 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentId', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('isResolved', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('incidentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentCommentsId', to='incidents.incident')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userCommentsId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
